// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD4QgSYKcUXZ1Na4kbZ5YaCiCy7M5Ldps',
    appId: '1:975222951117:web:060a045f0cad8dc4fc2d84',
    messagingSenderId: '975222951117',
    projectId: 'give-me-a-sign-a2b37',
    authDomain: 'give-me-a-sign-a2b37.firebaseapp.com',
    storageBucket: 'give-me-a-sign-a2b37.appspot.com',
    measurementId: 'G-RBRV2PBV3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCau6DMgeOsGYL6gw1z83X6zdBYgDyMTBc',
    appId: '1:975222951117:android:ba97fb3d7a993201fc2d84',
    messagingSenderId: '975222951117',
    projectId: 'give-me-a-sign-a2b37',
    storageBucket: 'give-me-a-sign-a2b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCr_9fci3cd1n-C0sWo94hcei2SDy4p34',
    appId: '1:975222951117:ios:33e411d66358369dfc2d84',
    messagingSenderId: '975222951117',
    projectId: 'give-me-a-sign-a2b37',
    storageBucket: 'give-me-a-sign-a2b37.appspot.com',
    iosClientId: '975222951117-ah8bn8aonshh3rst3nq30r1tptis59fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCr_9fci3cd1n-C0sWo94hcei2SDy4p34',
    appId: '1:975222951117:ios:33e411d66358369dfc2d84',
    messagingSenderId: '975222951117',
    projectId: 'give-me-a-sign-a2b37',
    storageBucket: 'give-me-a-sign-a2b37.appspot.com',
    iosClientId: '975222951117-ah8bn8aonshh3rst3nq30r1tptis59fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD4QgSYKcUXZ1Na4kbZ5YaCiCy7M5Ldps',
    appId: '1:975222951117:web:060a045f0cad8dc4fc2d84',
    messagingSenderId: '975222951117',
    projectId: 'give-me-a-sign-a2b37',
    authDomain: 'give-me-a-sign-a2b37.firebaseapp.com',
    storageBucket: 'give-me-a-sign-a2b37.appspot.com',
    measurementId: 'G-RBRV2PBV3R',
  );

}